### ISSUE TITLE
Only procedures with translations display them, others do not.

### ISSUE THREAD

**Issue by kriskleva** [medselfed/api-blueprint#2]
Comparing procedures we have cases where we've planned on producing multiple translations and many we have not.

New procedures like https://github.com/medselfed/api-blueprint/blob/master/apiary.apib#L262 have english and Spanish titles.  However, older titles  https://github.com/medselfed/api-blueprint/blob/master/apiary.apib#L82  do not.

The goal of this update will be to enable all current and past procedures to adopt an array of possible translations.

**Comment by azizalibasic** [comment]
@kriskleva Can we set a milestone date for when we expect this to be completed?
